
name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build-1:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-2:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-3:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-4:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-5:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-6:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-7:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-8:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-9:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-10:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-11:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-12:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-13:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-14:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-15:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-16:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-17:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-18:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-19:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-20:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-21:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-22:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-23:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-24:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-25:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-26:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-27:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-28:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-29:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3

  build-30:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUM=32 ngthvan1612/bench-test:v3
